services:
  db:
    image: docker.io/postgres:17-alpine
    container_name: payment_server_db
    # restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  alpha-vantage:
    image: docker.io/mikaak/alpha-vantage:latest
    platform: linux/arm64
    container_name: payment_server_alpha-vantage
    # restart: always
    ports:
      - 4001:4000
